---
info:
  title: Pydomdisco
  description: A fast async domain discovery tool written in Rust
  x-cortex-git:
    github:
      alias: intsightsorg
      repository: Intsights/pydomdisco
  x-cortex-tag: pydomdisco
  x-cortex-type: service
  x-cortex-domain-parents:
  - tag: threatintel-platform-delivery
  x-cortex-groups:
  - exposure:external-ship
  - target:library
openapi: 3.0.1
servers:
- url: "/"
